# Generated by Django 3.2.6 on 2022-03-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPrecipitationValue', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasOccupancy', models.TextField(null=True)),
                ('hasDescription', models.TextField(blank=True, null=True)),
                ('isAbandoned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasName', models.CharField(blank=True, max_length=80)),
                ('hasTelephoneNumber', models.TextField(blank=True)),
                ('hasMobileNumber', models.TextField(blank=True)),
                ('hasEmail', models.TextField(blank=True)),
                ('hasPhysicalAddress', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDistanceFromIncidentBuilding', models.FloatField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSize', models.FloatField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMaterialOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasCondition', models.TextField(blank=True)),
                ('hasSlope', models.FloatField(blank=True)),
                ('hasStatus', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
                ('hasMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
        ),
        migrations.CreateModel(
            name='SurroundingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDistanceFromIncidentBuilding', models.FloatField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurroundingTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSlope', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasFireFlow', models.FloatField(blank=True)),
                ('isFunctional', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPrecipitationValue', models.FloatField(blank=True)),
                ('hasRelativeHumidity', models.FloatField(blank=True)),
                ('hasTemperature', models.FloatField(blank=True)),
                ('hasTimeMark', models.TimeField(blank=True)),
                ('hasWindDirection', models.TextField(blank=True)),
                ('hasWindSpeed', models.FloatField(blank=True)),
                ('hasWindSpeeds', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSystemAnnunciatorPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='AreaOfRefuge',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
                ('hasStreetAddress', models.TextField(null=True)),
                ('hasPostalCode', models.IntegerField(null=True)),
                ('hasCity', models.TextField(null=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='BuildingEngineerContactAddress',
            fields=[
                ('contactaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.contactaddress')),
            ],
            bases=('Firefighters_data_Integration_Platform.contactaddress',),
        ),
        migrations.CreateModel(
            name='BuildingManagerContactAddress',
            fields=[
                ('contactaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.contactaddress')),
            ],
            bases=('Firefighters_data_Integration_Platform.contactaddress',),
        ),
        migrations.CreateModel(
            name='BuildingSafetySystem',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='BuildingUtilitySystem',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('isUtilityRunning', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='DoorUnlockingSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='ElevatorOverrideControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='EmergencyServiceProviderContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='ExtremelyValuableMaterial',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='FarsControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='FireDepartmentCommunicationSystemPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='FireLane',
            fields=[
                ('road_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.road')),
                ('hasAccessBarrierType', models.TextField(blank=True)),
                ('hasAnglesOfApproach', models.FloatField(blank=True)),
                ('hasTurningRadius', models.FloatField(blank=True)),
                ('hasVerticalClearance', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.road',),
        ),
        migrations.CreateModel(
            name='FireServiceOrganization',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='HazardousMaterial',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasHazardLevel', models.IntegerField(blank=True)),
                ('hasSpecialHazard', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='HazardousSubstance',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasHazardLevel', models.IntegerField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasSpecialHazard', models.TextField(blank=True)),
                ('isDecontaminationRequired', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Helipad',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='KeyBox',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasKey', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='MassNotificationSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='MunicipalDistributionSystem',
            fields=[
                ('watersource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.watersource')),
                ('hasPressure', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.watersource',),
        ),
        migrations.CreateModel(
            name='NonStructuralElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasID', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasFireResistanceRating', models.FloatField(blank=True)),
                ('hasMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Obstruction',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='OwnerContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasArea', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='PoliceDepartment',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='PublicSafetyAgencyContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='RoadToIncident',
            fields=[
                ('road_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.road')),
                ('hasTrafficLevel', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.road',),
        ),
        migrations.CreateModel(
            name='RoofTopElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='SmokeControlSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='StaticWaterSource',
            fields=[
                ('watersource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.watersource')),
                ('hasDistanceFromFDC', models.FloatField(blank=True)),
                ('hasDistanceFromIncidentBuilding', models.FloatField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.watersource',),
        ),
        migrations.CreateModel(
            name='UtilityContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='UtilityControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='Vegetation',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasFlammabilityLevel', models.IntegerField(blank=True)),
                ('hasSpecies', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='FireCommandCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasKeyLocated', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('contains', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticFireExtinguishingSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasLocationOfControlValve', models.TextField(blank=True)),
                ('isSystemActivated', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='BackUpPowerSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='EmergencyPowerOutlet',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='ExteriorDoor',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='ExteriorWall',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='ExteriorWindow',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='FireandSmokeProtectionElement',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasFireResistanceRating', models.FloatField(blank=True)),
                ('hasMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FirePump',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
                ('hasEnclosedArea', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='FloorAssembly',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('isLightweightConstruction', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='GasSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='HvacSystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='PortableFireExtinguisher',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasFireExtinguisherRating', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='PrimaryPowerSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='RoofAssembly',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('isAccessible', models.BooleanField(blank=True)),
                ('isLightweightConstruction', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='SensorDetector',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('isInAlarm', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='SmokeandHeatRemovalSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('isSystemActivated', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='StandpipeSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasClass', models.TextField(blank=True)),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasIsolationValveLocation', models.TextField(blank=True)),
                ('hasRequiredMaximumPressure', models.FloatField(blank=True)),
                ('hasRequiredMinimumPressure', models.FloatField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('isIsolationValveOpen', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasThickness', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='WaterSupplyandSewerageSystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasHeight', models.FloatField(blank=True)),
                ('hasOpeningDirection', models.TextField(blank=True)),
                ('isFunctional', models.BooleanField(blank=True)),
                ('isOnExterior', models.BooleanField(blank=True)),
                ('isShaftway', models.BooleanField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='StructuralElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasFireResistanceRating', models.FloatField(blank=True)),
                ('hasMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='IncidentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDemography', models.TextField(blank=True)),
                ('contains', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.surroundingterrain')),
                ('hasWeatherCondition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.weathercondition')),
                ('hasAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.publicsafetyagencycontactaddress')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasBuildingArea', models.FloatField(blank=True)),
                ('hasBuildingAreaUnit', models.CharField(blank=True, max_length=80)),
                ('hasBuildingHeight', models.FloatField(blank=True)),
                ('hasBuildingHeightUnit', models.CharField(blank=True, max_length=80)),
                ('hasCondition', models.TextField(blank=True)),
                ('includeHazardousOperation', models.BooleanField(blank=True)),
                ('hasNumberOfExit', models.IntegerField(blank=True)),
                ('hasNumberOfStory', models.IntegerField(blank=True)),
                ('hasNumberOfSublevel', models.IntegerField(blank=True)),
                ('hasOccupantLoad', models.IntegerField(blank=True)),
                ('hasBuildingPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingplan')),
                ('hasComponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasConstructionType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.constructiontype')),
                ('hasOccupancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingoccupancy')),
                ('hasAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='FireHydrant',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDistanceFromFDC', models.FloatField(blank=True)),
                ('hasFireFlow', models.FloatField(blank=True)),
                ('hasNumberOfOutlet', models.IntegerField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('isFunctional', models.BooleanField(blank=True)),
                ('hasHoseConnection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.watersource')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.AddField(
            model_name='emergencyserviceprovider',
            name='hasAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.emergencyserviceprovidercontactaddress'),
        ),
        migrations.AddField(
            model_name='buildingutilitysystem',
            name='hasAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.utilitycontactaddress'),
        ),
        migrations.AddField(
            model_name='buildingutilitysystem',
            name='hasControlPanel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.utilitycontrolpanel'),
        ),
        migrations.CreateModel(
            name='AlternativeAutomaticFireExtinguishingSystem',
            fields=[
                ('automaticfireextinguishingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.automaticfireextinguishingsystem',),
        ),
        migrations.CreateModel(
            name='AutomaticSprinklerSystem',
            fields=[
                ('automaticfireextinguishingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
                ('hasRequiredMaximumPressure', models.FloatField(blank=True)),
                ('hasRequiredMinimumPressure', models.FloatField(blank=True)),
                ('isControlValveOn', models.BooleanField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.automaticfireextinguishingsystem',),
        ),
        migrations.CreateModel(
            name='CarbonMonoxideDetector',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='CbrSensor',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='FireBarrier',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='FirePartition',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='GasDetector',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='ShaftEnclosure',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='SmokeBarrier',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='SmokePartition',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField(blank=True)),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='Stairway',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasDirectionToExit', models.TextField(blank=True)),
                ('hasDischargeLevel', models.TextField(blank=True)),
                ('hasFloorsServed', models.TextField(blank=True)),
                ('isRoofAccess', models.BooleanField(blank=True)),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasExitTravelDistances', models.FloatField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
                ('isExit', models.BooleanField(blank=True)),
                ('hasFireExtinguishingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='SmokeControlSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('isSystemActivated', models.BooleanField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.smokecontrolsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Ramp',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasDirectionToExit', models.TextField(blank=True)),
                ('hasDischargeLevel', models.TextField(blank=True)),
                ('hasFloorsServed', models.TextField(blank=True)),
                ('isRoofAccess', models.BooleanField(blank=True)),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasExitTravelDistances', models.FloatField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
                ('isExit', models.BooleanField(blank=True)),
                ('hasFireExtinguishingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='MassNotificationSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasType', models.TextField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.massnotificationsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireHoseConnection',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField(blank=True)),
                ('hasHoseConnection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.standpipesystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireDepartmentConnection',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasDistanceFromWaterSource', models.FloatField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasNumberOfInlet', models.IntegerField(blank=True)),
                ('hasHoseConnection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.watersource')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireAlarmSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField(blank=True)),
                ('hasTypeOfSignalInitiator', models.TextField(blank=True)),
                ('isSystemActivated', models.BooleanField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.alarmsystemannunciatorpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FarsFillStation',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasFillPressure', models.FloatField(blank=True)),
                ('hasFillTime', models.FloatField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasNumberOfSimultaneousFill', models.IntegerField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.farscontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField(blank=True)),
                ('hasDischargeLevel', models.TextField(blank=True)),
                ('hasFloorsServed', models.TextField(blank=True)),
                ('hasMachineRoomLocation', models.TextField(blank=True)),
                ('isFunctional', models.BooleanField(blank=True)),
                ('isQualifiedForEvacuation', models.BooleanField(blank=True)),
                ('hasExitTravelDistances', models.FloatField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.elevatoroverridecontrolpanel')),
                ('hasFireExtinguishingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasOpeningDirection', models.TextField(blank=True)),
                ('isFunctional', models.BooleanField(blank=True)),
                ('isPrimaryFireServiceEntryPoint', models.BooleanField(blank=True)),
                ('isShaftway', models.BooleanField(blank=True)),
                ('hasExitTravelDistances', models.FloatField(blank=True)),
                ('hasWidth', models.FloatField(blank=True)),
                ('isExit', models.BooleanField(blank=True)),
                ('hasControlPanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.doorunlockingsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='ConcealedSpace',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasFireExtinguishingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.AddField(
            model_name='automaticfireextinguishingsystem',
            name='hasConnectionWith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.firealarmsystem'),
        ),
        migrations.CreateModel(
            name='VerticalOpening',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField(blank=True)),
                ('hasLocation', models.TextField(blank=True)),
                ('hasShaftEnclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.shaftenclosure')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
    ]
