# Generated by Django 4.0.2 on 2022-02-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firefighters_data_Integration_Platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
