# Generated by Django 4.0.2 on 2022-02-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firefighters_data_Integration_Platform', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='BuildingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingEngineerContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='BuildingManagerContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='BuildingOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.TextField()),
                ('isAbandoned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.TextField()),
                ('hasType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDescription', models.TextField()),
                ('hasLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDistanceFromIncidentBuilding', models.FloatField()),
                ('hasLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyServiceProviderContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='HoseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSize', models.FloatField()),
                ('hasType', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMaterialOf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='PublicSafetyAgencyContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasCondition', models.TextField()),
                ('hasSlope', models.FloatField()),
                ('hasStatus', models.TextField()),
                ('hasType', models.TextField()),
                ('hasWidth', models.FloatField()),
                ('hasMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
        ),
        migrations.CreateModel(
            name='SurroundingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDistanceFromIncidentBuilding', models.FloatField()),
                ('hasLocation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurroundingTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSlope', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UtilityContactAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.address')),
            ],
            bases=('Firefighters_data_Integration_Platform.address',),
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasFireFlow', models.FloatField()),
                ('isFunctional', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasPrecipitationValue', models.FloatField()),
                ('hasRelativeHumidity', models.FloatField()),
                ('hasTemperature', models.FloatField()),
                ('hasTimeMark', models.TimeField()),
                ('hasWindDirection', models.TextField()),
                ('hasWindSpeed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSystemAnnunciatorPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='AreaOfRefuge',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasCapacity', models.IntegerField()),
                ('hasLocation', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='BuildingSafetySystem',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='BuildingUtilitySystem',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('isUtilityRunning', models.BooleanField()),
                ('hasAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.utilitycontactaddress')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='DoorUnlockingSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='ElevatorOverrideControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='ExtremelyValuableMaterial',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='FarsControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='FireDepartmentCommunicationSystemPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='FireLane',
            fields=[
                ('road_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.road')),
                ('hasAccessBarrierType', models.TextField()),
                ('hasAnglesOfApproach', models.FloatField()),
                ('hasTurningRadius', models.FloatField()),
                ('hasVerticalClearance', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.road',),
        ),
        migrations.CreateModel(
            name='FireServiceOrganization',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='HazardousMaterial',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDescription', models.TextField()),
                ('hasHazardLevel', models.IntegerField()),
                ('hasSpecialHazard', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='HazardousSubstance',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField()),
                ('hasHazardLevel', models.IntegerField()),
                ('hasLocation', models.TextField()),
                ('hasSpecialHazard', models.TextField()),
                ('isDecontaminationRequired', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Helipad',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='KeyBox',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasKey', models.TextField()),
                ('hasLocation', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='MassNotificationSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='MunicipalDistributionSystem',
            fields=[
                ('watersource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.watersource')),
                ('hasPressure', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.watersource',),
        ),
        migrations.CreateModel(
            name='NonStructuralElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasID', models.TextField()),
                ('hasLocation', models.TextField()),
                ('hasFireResistanceRating', models.FloatField()),
                ('hasMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='Obstruction',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDescription', models.TextField()),
                ('hasType', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasArea', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='PoliceDepartment',
            fields=[
                ('emergencyserviceprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.emergencyserviceprovider')),
            ],
            bases=('Firefighters_data_Integration_Platform.emergencyserviceprovider',),
        ),
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='RoadToIncident',
            fields=[
                ('road_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.road')),
                ('hasTrafficLevel', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.road',),
        ),
        migrations.CreateModel(
            name='RoofTopElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField()),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='SmokeControlSystemControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='StaticWaterSource',
            fields=[
                ('watersource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.watersource')),
                ('hasDistanceFromFDC', models.FloatField()),
                ('hasDistanceFromIncidentBuilding', models.FloatField()),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.watersource',),
        ),
        migrations.CreateModel(
            name='UtilityControlPanel',
            fields=[
                ('controlpanel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.controlpanel',),
        ),
        migrations.CreateModel(
            name='Vegetation',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasFlammabilityLevel', models.IntegerField()),
                ('hasSpecies', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.CreateModel(
            name='IncidentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasDemography', models.TextField()),
                ('contains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.surroundingterrain')),
                ('hasAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.publicsafetyagencycontactaddress')),
                ('hasWeatherCondition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.weathercondition')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasBuildingArea', models.FloatField()),
                ('hasBuildingHeight', models.FloatField()),
                ('hasCondition', models.TextField()),
                ('includeHazardousOperation', models.BooleanField()),
                ('hasNumberOfExit', models.IntegerField()),
                ('hasNumberOfStory', models.IntegerField()),
                ('hasNumberOfSublevel', models.IntegerField()),
                ('hasOccupantLoad', models.IntegerField()),
                ('hasAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.address')),
                ('hasBuildingPlan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingplan')),
                ('hasComponent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasConstructionType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.constructiontype')),
                ('hasOccupancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.buildingoccupancy')),
            ],
        ),
        migrations.CreateModel(
            name='FireCommandCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasKeyLocated', models.TextField()),
                ('hasLocation', models.TextField()),
                ('contains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.controlpanel')),
            ],
        ),
        migrations.AddField(
            model_name='emergencyserviceprovider',
            name='hasAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.emergencyserviceprovidercontactaddress'),
        ),
        migrations.CreateModel(
            name='AutomaticFireExtinguishingSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('hasLocationOfControlValve', models.TextField()),
                ('isSystemActivated', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='BackUpPowerSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField()),
                ('hasWidth', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='EmergencyPowerOutlet',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='ExteriorDoor',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='ExteriorWall',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='ExteriorWindow',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='FireandSmokeProtectionElement',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField()),
                ('hasFireResistanceRating', models.FloatField()),
                ('hasMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FirePump',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('facade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.facade')),
                ('hasEnclosedArea', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.facade',),
        ),
        migrations.CreateModel(
            name='FloorAssembly',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('isLightweightConstruction', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='GasSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Hallway',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField()),
                ('hasWidth', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='HvacSystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='PortableFireExtinguisher',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasFireExtinguisherRating', models.TextField()),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='PrimaryPowerSupplySystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='RoofAssembly',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('isAccessible', models.BooleanField()),
                ('isLightweightConstruction', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='SensorDetector',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('isInAlarm', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='SmokeandHeatRemovalSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField()),
                ('hasType', models.TextField()),
                ('isSystemActivated', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='StandpipeSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasClass', models.TextField()),
                ('hasCoverageZone', models.TextField()),
                ('hasIsolationValveLocation', models.TextField()),
                ('hasRequiredMaximumPressure', models.FloatField()),
                ('hasRequiredMinimumPressure', models.FloatField()),
                ('hasType', models.TextField()),
                ('isIsolationValveOpen', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasThickness', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='WaterSupplyandSewerageSystem',
            fields=[
                ('buildingutilitysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingutilitysystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingutilitysystem',),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasHeight', models.FloatField()),
                ('hasOpeningDirection', models.TextField()),
                ('isFunctional', models.BooleanField()),
                ('isOnExterior', models.BooleanField()),
                ('isShaftway', models.BooleanField()),
                ('hasWidth', models.FloatField()),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='StructuralElement',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasLocation', models.TextField()),
                ('hasFireResistanceRating', models.FloatField()),
                ('hasMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.material')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.CreateModel(
            name='FireHydrant',
            fields=[
                ('surroundingstructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.surroundingstructure')),
                ('hasDistanceFromFDC', models.FloatField()),
                ('hasFireFlow', models.FloatField()),
                ('hasNumberOfOutlet', models.IntegerField()),
                ('hasType', models.TextField()),
                ('isFunctional', models.BooleanField()),
                ('hasHoseConnection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.watersource')),
            ],
            bases=('Firefighters_data_Integration_Platform.surroundingstructure',),
        ),
        migrations.AddField(
            model_name='buildingutilitysystem',
            name='hasControlPanel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.utilitycontrolpanel'),
        ),
        migrations.CreateModel(
            name='AlternativeAutomaticFireExtinguishingSystem',
            fields=[
                ('automaticfireextinguishingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.automaticfireextinguishingsystem',),
        ),
        migrations.CreateModel(
            name='AutomaticSprinklerSystem',
            fields=[
                ('automaticfireextinguishingsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
                ('hasRequiredMaximumPressure', models.FloatField()),
                ('hasRequiredMinimumPressure', models.FloatField()),
                ('isControlValveOn', models.BooleanField()),
            ],
            bases=('Firefighters_data_Integration_Platform.automaticfireextinguishingsystem',),
        ),
        migrations.CreateModel(
            name='CarbonMonoxideDetector',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='CbrSensor',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='FireBarrier',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='FirePartition',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='GasDetector',
            fields=[
                ('sensordetector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.sensordetector')),
            ],
            bases=('Firefighters_data_Integration_Platform.sensordetector',),
        ),
        migrations.CreateModel(
            name='ShaftEnclosure',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='SmokeBarrier',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='SmokePartition',
            fields=[
                ('fireandsmokeprotectionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.fireandsmokeprotectionelement')),
                ('hasEnclosedArea', models.TextField()),
            ],
            bases=('Firefighters_data_Integration_Platform.fireandsmokeprotectionelement',),
        ),
        migrations.CreateModel(
            name='Stairway',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasDirectionToExit', models.TextField()),
                ('hasDischargeLevel', models.TextField()),
                ('hasFloorsServed', models.TextField()),
                ('isRoofAccess', models.BooleanField()),
                ('hasCapacity', models.IntegerField()),
                ('hasExitTravelDistances', models.FloatField()),
                ('hasWidth', models.FloatField()),
                ('isExit', models.BooleanField()),
                ('hasFireExtinguishingSystem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='SmokeControlSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('hasType', models.TextField()),
                ('isSystemActivated', models.BooleanField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.smokecontrolsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Ramp',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasDirectionToExit', models.TextField()),
                ('hasDischargeLevel', models.TextField()),
                ('hasFloorsServed', models.TextField()),
                ('isRoofAccess', models.BooleanField()),
                ('hasCapacity', models.IntegerField()),
                ('hasExitTravelDistances', models.FloatField()),
                ('hasWidth', models.FloatField()),
                ('isExit', models.BooleanField()),
                ('hasFireExtinguishingSystem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='MassNotificationSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('hasType', models.TextField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.massnotificationsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireHoseConnection',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasLocation', models.TextField()),
                ('hasHoseConnection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.standpipesystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireDepartmentConnection',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('hasDistanceFromWaterSource', models.FloatField()),
                ('hasLocation', models.TextField()),
                ('hasNumberOfInlet', models.IntegerField()),
                ('hasHoseConnection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.hoseconnection')),
                ('hasWaterSource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.watersource')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FireAlarmSystem',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasCoverageZone', models.TextField()),
                ('hasTypeOfSignalInitiator', models.TextField()),
                ('isSystemActivated', models.BooleanField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.alarmsystemannunciatorpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='FarsFillStation',
            fields=[
                ('buildingsafetysystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingsafetysystem')),
                ('hasFillPressure', models.FloatField()),
                ('hasFillTime', models.FloatField()),
                ('hasLocation', models.TextField()),
                ('hasNumberOfSimultaneousFill', models.IntegerField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.farscontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingsafetysystem',),
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasCapacity', models.IntegerField()),
                ('hasDischargeLevel', models.TextField()),
                ('hasFloorsServed', models.TextField()),
                ('hasMachineRoomLocation', models.TextField()),
                ('isFunctional', models.BooleanField()),
                ('isQualifiedForEvacuation', models.BooleanField()),
                ('hasExitTravelDistances', models.FloatField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.elevatoroverridecontrolpanel')),
                ('hasFireExtinguishingSystem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('nonstructuralelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.nonstructuralelement')),
                ('hasOpeningDirection', models.TextField()),
                ('isFunctional', models.BooleanField()),
                ('isPrimaryFireServiceEntryPoint', models.BooleanField()),
                ('isShaftway', models.BooleanField()),
                ('hasExitTravelDistances', models.FloatField()),
                ('hasWidth', models.FloatField()),
                ('isExit', models.BooleanField()),
                ('hasControlPanel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.doorunlockingsystemcontrolpanel')),
            ],
            bases=('Firefighters_data_Integration_Platform.nonstructuralelement',),
        ),
        migrations.CreateModel(
            name='ConcealedSpace',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField()),
                ('hasLocation', models.TextField()),
                ('hasFireExtinguishingSystem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.automaticfireextinguishingsystem')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
        migrations.AddField(
            model_name='automaticfireextinguishingsystem',
            name='hasConnectionWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.firealarmsystem'),
        ),
        migrations.CreateModel(
            name='VerticalOpening',
            fields=[
                ('buildingcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Firefighters_data_Integration_Platform.buildingcomponent')),
                ('hasDescription', models.TextField()),
                ('hasLocation', models.TextField()),
                ('hasShaftEnclosure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firefighters_data_Integration_Platform.shaftenclosure')),
            ],
            bases=('Firefighters_data_Integration_Platform.buildingcomponent',),
        ),
    ]
