# AlternativeAutomaticFireExtinguishingSystem

def add(request):

	alternativeAutomaticFireExtinguishingSystem = AlternativeAutomaticFireExtinguishingSystem(	alternativeAutomaticFireExtinguishingSystem.save()